[2025-08-01T08:59:17.795-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-01T08:59:17.804-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp_bq manual__2025-08-01T11:59:16.585236+00:00 [queued]>
[2025-08-01T08:59:17.808-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp_bq manual__2025-08-01T11:59:16.585236+00:00 [queued]>
[2025-08-01T08:59:17.808-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-01T08:59:17.815-0300] {taskinstance.py:2330} INFO - Executing <Task(BigQueryInsertJobOperator): criar_tabela_temp_bq> on 2025-08-01 11:59:16.585236+00:00
[2025-08-01T08:59:17.820-0300] {standard_task_runner.py:63} INFO - Started process 1235 to run task
[2025-08-01T08:59:17.822-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exportar_bq_para_gcs_csv', 'criar_tabela_temp_bq', 'manual__2025-08-01T11:59:16.585236+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/notas_ordem.py', '--cfg-path', '/tmp/tmp235fsqbr']
[2025-08-01T08:59:17.823-0300] {standard_task_runner.py:91} INFO - Job 61: Subtask criar_tabela_temp_bq
[2025-08-01T08:59:17.848-0300] {task_command.py:426} INFO - Running <TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp_bq manual__2025-08-01T11:59:16.585236+00:00 [running]> on host 7b4a21630117
[2025-08-01T08:59:17.894-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exportar_bq_para_gcs_csv' AIRFLOW_CTX_TASK_ID='criar_tabela_temp_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T11:59:16.585236+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-01T11:59:16.585236+00:00'
[2025-08-01T08:59:17.895-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-01T08:59:17.901-0300] {connection.py:513} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 508, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/secrets/base_secrets.py", line 68, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 564, in from_json
    return Connection(conn_id=conn_id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'extra__google_cloud_platform__project'
[2025-08-01T08:59:17.907-0300] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-08-01T08:59:17.908-0300] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-08-01T08:59:17.908-0300] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-08-01T08:59:17.944-0300] {bigquery.py:2832} INFO - Executing: {'query': {'query': '\n                    CREATE OR REPLACE TABLE `sz-00022-ws.PLAMI.TMP_NOTAS_ORDENS` AS\n                    SELECT * FROM `sz-00022-ws.PLAMI.NOTAS_ORDENS` limit 10;\n                ', 'useLegacySql': False}}'
[2025-08-01T08:59:17.945-0300] {bigquery.py:1660} INFO - Inserting job ***_exportar_bq_para_gcs_csv_criar_tabela_temp_bq_2025_08_01T11_59_16_585236_00_00_0c4604cf8bc867922326d0f8c06e0840
[2025-08-01T08:59:34.216-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-01T08:59:34.230-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exportar_bq_para_gcs_csv, task_id=criar_tabela_temp_bq, run_id=manual__2025-08-01T11:59:16.585236+00:00, execution_date=20250801T115916, start_date=20250801T115917, end_date=20250801T115934
[2025-08-01T08:59:34.275-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-01T08:59:34.301-0300] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-01T08:59:34.302-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
