[2025-08-08T14:12:51.506-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-08T14:12:51.523-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: avisos_coordenador.consultar_valores_pi manual__2025-08-08T17:12:49.798034+00:00 [queued]>
[2025-08-08T14:12:51.527-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: avisos_coordenador.consultar_valores_pi manual__2025-08-08T17:12:49.798034+00:00 [queued]>
[2025-08-08T14:12:51.528-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-08T14:12:51.534-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): consultar_valores_pi> on 2025-08-08 17:12:49.798034+00:00
[2025-08-08T14:12:51.537-0300] {standard_task_runner.py:63} INFO - Started process 7306 to run task
[2025-08-08T14:12:51.539-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'avisos_coordenador', 'consultar_valores_pi', 'manual__2025-08-08T17:12:49.798034+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/avisos_coordenador.py', '--cfg-path', '/tmp/tmpfcy7lkty']
[2025-08-08T14:12:51.540-0300] {standard_task_runner.py:91} INFO - Job 100: Subtask consultar_valores_pi
[2025-08-08T14:12:51.565-0300] {task_command.py:426} INFO - Running <TaskInstance: avisos_coordenador.consultar_valores_pi manual__2025-08-08T17:12:49.798034+00:00 [running]> on host 6c187a0d27dc
[2025-08-08T14:12:51.610-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='avisos_coordenador' AIRFLOW_CTX_TASK_ID='consultar_valores_pi' AIRFLOW_CTX_EXECUTION_DATE='2025-08-08T17:12:49.798034+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-08T17:12:49.798034+00:00'
[2025-08-08T14:12:51.611-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-08T14:12:52.093-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-08T14:12:52.094-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/avisos_coordenador.py", line 108, in consultar_valores_pi
    pode, proximo = pode_disparar(conn, id_alarme, cooldown_minutos)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/avisos_coordenador.py", line 27, in pode_disparar
    if row and row[0] and row[0] > agora:
                          ^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
[2025-08-08T14:12:52.105-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=avisos_coordenador, task_id=consultar_valores_pi, run_id=manual__2025-08-08T17:12:49.798034+00:00, execution_date=20250808T171249, start_date=20250808T171251, end_date=20250808T171252
[2025-08-08T14:12:52.112-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 100 for task consultar_valores_pi (can't compare offset-naive and offset-aware datetimes; 7306)
[2025-08-08T14:12:52.152-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-08T14:12:52.162-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-08T14:12:52.163-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
