[2025-07-31T16:52:03.947-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T16:52:03.957-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp manual__2025-07-31T19:52:03.040474+00:00 [queued]>
[2025-07-31T16:52:03.961-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp manual__2025-07-31T19:52:03.040474+00:00 [queued]>
[2025-07-31T16:52:03.961-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T16:52:03.969-0300] {taskinstance.py:2330} INFO - Executing <Task(BigQueryInsertJobOperator): criar_tabela_temp> on 2025-07-31 19:52:03.040474+00:00
[2025-07-31T16:52:03.976-0300] {standard_task_runner.py:63} INFO - Started process 272 to run task
[2025-07-31T16:52:03.978-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exportar_bq_para_gcs_csv', 'criar_tabela_temp', 'manual__2025-07-31T19:52:03.040474+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/notas_ordem.py', '--cfg-path', '/tmp/tmplj0oy5_s']
[2025-07-31T16:52:03.979-0300] {standard_task_runner.py:91} INFO - Job 4: Subtask criar_tabela_temp
[2025-07-31T16:52:04.005-0300] {task_command.py:426} INFO - Running <TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp manual__2025-07-31T19:52:03.040474+00:00 [running]> on host 2778f3f60c85
[2025-07-31T16:52:04.054-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exportar_bq_para_gcs_csv' AIRFLOW_CTX_TASK_ID='criar_tabela_temp' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T19:52:03.040474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T19:52:03.040474+00:00'
[2025-07-31T16:52:04.055-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T16:52:04.064-0300] {connection.py:513} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 508, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/secrets/base_secrets.py", line 68, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 564, in from_json
    return Connection(conn_id=conn_id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'extra__google_cloud_platform__project'
[2025-07-31T16:52:04.070-0300] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-07-31T16:52:04.070-0300] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-07-31T16:52:04.070-0300] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-07-31T16:52:04.106-0300] {bigquery.py:2832} INFO - Executing: {'query': {'query': '\n                    CREATE OR REPLACE TABLE `sz-00022-ws.PLAMI.TMP_NOTAS_ORDENS` AS\n                    SELECT * FROM `sz-00022-ws.PLAMI.NOTAS_ORDENS`;\n                ', 'useLegacySql': False}}'
[2025-07-31T16:52:04.106-0300] {bigquery.py:1660} INFO - Inserting job ***_exportar_bq_para_gcs_csv_criar_tabela_temp_2025_07_31T19_52_03_040474_00_00_b60cbd48f727f1ff013483311bd5e8fe
[2025-07-31T16:52:21.743-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T16:52:21.757-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exportar_bq_para_gcs_csv, task_id=criar_tabela_temp, run_id=manual__2025-07-31T19:52:03.040474+00:00, execution_date=20250731T195203, start_date=20250731T195203, end_date=20250731T195221
[2025-07-31T16:52:21.806-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-31T16:52:21.820-0300] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-31T16:52:21.821-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
