[2025-07-31T18:30:21.650-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T18:30:21.659-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp manual__2025-07-31T21:30:20.503535+00:00 [queued]>
[2025-07-31T18:30:21.663-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp manual__2025-07-31T21:30:20.503535+00:00 [queued]>
[2025-07-31T18:30:21.663-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T18:30:21.669-0300] {taskinstance.py:2330} INFO - Executing <Task(BigQueryInsertJobOperator): criar_tabela_temp> on 2025-07-31 21:30:20.503535+00:00
[2025-07-31T18:30:21.674-0300] {standard_task_runner.py:63} INFO - Started process 650 to run task
[2025-07-31T18:30:21.676-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exportar_bq_para_gcs_csv', 'criar_tabela_temp', 'manual__2025-07-31T21:30:20.503535+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/notas_ordem.py', '--cfg-path', '/tmp/tmp7qk4_dt7']
[2025-07-31T18:30:21.677-0300] {standard_task_runner.py:91} INFO - Job 57: Subtask criar_tabela_temp
[2025-07-31T18:30:21.700-0300] {task_command.py:426} INFO - Running <TaskInstance: exportar_bq_para_gcs_csv.criar_tabela_temp manual__2025-07-31T21:30:20.503535+00:00 [running]> on host 7b4a21630117
[2025-07-31T18:30:21.745-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exportar_bq_para_gcs_csv' AIRFLOW_CTX_TASK_ID='criar_tabela_temp' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T21:30:20.503535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T21:30:20.503535+00:00'
[2025-07-31T18:30:21.746-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T18:30:21.752-0300] {connection.py:513} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 508, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/secrets/base_secrets.py", line 116, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/secrets/base_secrets.py", line 68, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 564, in from_json
    return Connection(conn_id=conn_id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'extra__google_cloud_platform__project'
[2025-07-31T18:30:21.757-0300] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-07-31T18:30:21.757-0300] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-07-31T18:30:21.758-0300] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-07-31T18:30:21.793-0300] {bigquery.py:2832} INFO - Executing: {'query': {'query': '\n                    CREATE OR REPLACE TABLE `sz-00022-ws.PLAMI.TMP_NOTAS_ORDENS` AS\n                    SELECT * FROM `sz-00022-ws.PLAMI.NOTAS_ORDENS`;\n                ', 'useLegacySql': False}}'
[2025-07-31T18:30:21.793-0300] {bigquery.py:1660} INFO - Inserting job ***_exportar_bq_para_gcs_csv_criar_tabela_temp_2025_07_31T21_30_20_503535_00_00_820336a621e35bc5e87e09647ad3b3a8
[2025-07-31T18:30:37.908-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T18:30:37.936-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exportar_bq_para_gcs_csv, task_id=criar_tabela_temp, run_id=manual__2025-07-31T21:30:20.503535+00:00, execution_date=20250731T213020, start_date=20250731T213021, end_date=20250731T213037
[2025-07-31T18:30:37.979-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-31T18:30:38.005-0300] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-31T18:30:38.007-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
